
project_id = "fyyzaysmpephomhmudxt"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.accept-invitation]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.invite-member-native]
verify_jwt = true
